### ISSUE TITLE
CSS support

### ISSUE THREAD

**Issue by benlongmire** [johnknoop/vscode-handlebars-preview#20]
Is CSS supported like this?
```html
<link rel="stylesheet" type="text/css" href="style.css" />
```
I'm not sure if I'm doing something wrong however I can't get CSS to load. I've tried absolute & relative file paths. CSS definitely works if added directly to the template so It's not the renderer. Image files load so it's not having trouble finding files. The only workaround I've found is using a partial, however that doesn't seem like a sustainable solution as it uses `<style></style>`

**Comment by benlongmire** [comment]
Update, I have realised that CSS is supported if the CSS is being served from a webserver, however locally it's not working.

```html
<!-- This doesn't work -->
<link rel="stylesheet" type="text/css" href="style.css" />
<!-- This does work -->
<link rel="stylesheet" type="text/css" href="http://example.com/style.css" />
```

**Comment by johnknoop** [comment]
Hi @benlongmire 

I don't think VS Code will pull in a local style sheet like that and apply it to the rendered html.

You can always include your local css file using handlebars include syntax. If I have a style sheet called "style.hbs" located in the "partials" folder, then this code will work:

```handlebars
{{>partials/style}}
```

**Comment by benlongmire** [comment]
@johnknoop I have raised a pull request that includes local CSS support. https://github.com/johnknoop/vscode-handlebars-preview/pull/21

**Comment by johnknoop** [comment]
@benlongmire 

I had to make a change in the repathing of images due to a change in the underlying API: https://github.com/johnknoop/vscode-handlebars-preview/commit/8dcd3b914100968da732a37bfd060e8eaad149d8

The repathing of CSS files was also broken, but I think I managed to fix it. Created this PR in case you wanna have a look: https://github.com/johnknoop/vscode-handlebars-preview/pull/24
